### PR TITLE
index.php: Use class name insted of alias

### PR DESCRIPTION
**Pull request by kubinpetr**

### CODE REVIEW

**Comment by dg** [comment]
Name is fine, why class name?

**Comment by kubinpetr** [comment]
I dont think so, that alias is good solution.
This is not good to:
```
$presenter->context->application;
$presenter->getByType('Nette\Application\Application');
```

**Comment by dg** [comment]
I don't understand.

**Comment by enumag** [comment]
@dg It's better to not rely on a service name. The alias will not exist in the future and then you'd have to duplicate the extension name. Solution with getByType will always work.

**Comment by Majkl578** [comment]
:+1: 
https://github.com/nette/application/commit/6437b558f805d047b3f5a49605e4c9214eba6cac is a good example of what @enumag is saying -- it deprecated the current name `application`.

**Comment by dg** [comment]
Why deprecated? Name still exists and can be used for altering service in configuration.

**Comment by enumag** [comment]
It only works if you don't change the extension name (which I always change in my app by the way - to nette.application).

Just merge it please, this indeed is a better practice. It's obviously best to not use extension and service names anywhere in your app and libs. The only exception to this rule is the config.neon file.

I don't want to spend more time commenting on this issue so I'll unsubscribe after this comment.

**Comment by dg** [comment]
I totaly agree except one thing: 

> It's obviously best to not use extension and service names anywhere in your app and libs. The only exception to this rule is the config.neon file.)

… and bootstrap & index. I.e. the composition root.

**Comment by fprochazka** [comment]
I support this. I think we should be teaching people to relly on types not on names.

**Comment by kubinpetr** [comment]
Thx guys @enumag @fprochazka

**Comment by dg** [comment]
@fprochazka it is false teaching, because here is usage of service name perfectly valid. And little fudging for good is not good. As in the case of static router factory.

**Comment by fprochazka** [comment]
@dg I agree it's valid. But using type is better.

**Comment by dg** [comment]
:+1:

**Pull request merged**
