### PR TITLE
log exception when bad link detected

### PR DESCRIPTION
**Pull request by VladaHejda**
When 404 occurred after pass through an anchor with referer on site self, it is probably bad link inside application self and not user's typo or search engine wrong index - it might be worth to send report.

### CODE REVIEW

**Comment by JanTvrdik** [comment]
:-1: too smart

**Comment by VladaHejda** [comment]
and what about log that exception when just **any** referer exists?

**Comment by enumag** [comment]
Why log entire exception? We can just add the referer information to access.log.

**Comment by VladaHejda** [comment]
but that 404 may be an error in application.. and who reads access log...

**Comment by enumag** [comment]
I do. And to prevent errors in application I use INVALID_LINK_EXCEPTION.

**Comment by VladaHejda** [comment]
what if programmer self throws `BadRequestException` because of invalid input parameter:
```php
function actionDefault($number) {
    if ($number > 3) {
        throw new BadRequestException;
    }
}
```
but `<a n:href="this number => 5">link</a>` is not invalid link...

**Comment by enumag** [comment]
That's exactly why I use [this approach](https://github.com/nette/application/pull/63).

**Comment by dg** [comment]
IMHO logging of 404 can be removed, it is usually done (in better way) by web server.

**Comment by VladaHejda** [comment]
@enumag: actually I don't see how that approach can solve the issued problem.

**Comment by TomasVotruba** [comment]
Is there any way to merge this or should we close this?

**Pull request closed without merging**
